[env]
TERM = "screen-256color"

[font]
size = 15

normal.family = "MesloLGLDZ Nerd Font"
bold.family = "MesloLGLDZ Nerd Font"
bold_italic.family = "MesloLGLDZ Nerd Font"
italic.family = "MesloLGLDZ Nerd Font"

offset.x = 0
offset.y = 0

glyph_offset.x = 0
glyph_offset.y = 0

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
option_as_alt = "Both"
opacity = 1.0
padding.x = 0
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]
