return {
  'lukas-reineke/indent-blankline.nvim',
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    buftype_exclude = { 'terminal', 'nofile' },
    filetype_exclude = {
      'help',
      'aerial',
      'terminal',
      'lspinfo',
      'TelescopePrompt',
      'TelescopeResults',
      'neogitstatus',
      'neo-tree',
      'noice',
      'lazy',
      'mason',
    },
    char = '│',
    use_treesitter = true,
    use_treesitter_scope = false,
    show_trailing_blankline_indent = false,
    show_current_context = true,
    show_current_context_start = false,
    context_patterns = {
      'class',
      'return',
      'function',
      'method',
      '^if',
      '^while',
      'jsx_element',
      '^for',
      '^object',
      '^table',
      'block',
      'arguments',
      'if_statement',
      'else_clause',
      'jsx_element',
      'jsx_self_closing_element',
      'try_statement',
      'catch_clause',
      'import_statement',
      'operation_type',
    },
  },
}
