local icons = require 'vasco.utils.icons'

return {
  -- 'nvim-neo-tree/neo-tree.nvim',
  -- branch = 'v3.x',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'nvim-tree/nvim-web-devicons',
  --   'MunifTanjim/nui.nvim',
  --   {
  --       's1n7ax/nvim-window-picker',
  --       version = '2.*',
  --       config = function()
  --           require 'window-picker'.setup({
  --               filter_rules = {
  --                   include_current_win = false,
  --                   autoselect_one = true,
  --                   -- filter using buffer options
  --                   bo = {
  --                       -- if the file type is one of following, the window will be ignored
  --                       filetype = { 'neo-tree', "neo-tree-popup", "notify" },
  --                       -- if the buffer type is one of following, the window will be ignored
  --                       buftype = { 'terminal', "quickfix" },
  --                   },
  --           },
  --       })
  --       end,
  --     },
  -- },
  -- cmd = 'Neotree',
  -- keys = {
  --   {
  --     '<leader>e',
  --     function()
  --       require('neo-tree.command').execute { toggle = true, dir = vim.loop.cwd() }
  --     end,
  --     desc = 'File explorer',
  --   },
  -- },
  --
  -- opts = {
  --   close_if_last_window = true, -- Close Neo-tree if it is the last window left in the tab
  --   -- popup_border_style = config.border.style,
  --   enable_git_status = true,
  --   enable_diagnostics = false,
  --   default_component_configs = {
  --     container = {
  --       enable_character_fade = true,
  --     },
  --     indent = {
  --       indent_size = 2,
  --       padding = 1, -- extra padding on left hand side
  --       -- indent guides
  --       with_markers = false,
  --       indent_marker = '│',
  --       last_indent_marker = '└',
  --       highlight = 'NeoTreeIndentMarker',
  --       -- expander config, needed for nesting files
  --       with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
  --       expander_collapsed = icons.right_arrow,
  --       expander_expanded = icons.down_arrow,
  --       expander_highlight = 'NeoTreeExpander',
  --     },
  --     icon = {
  --       folder_closed = icons.folder_closed,
  --       folder_open = icons.folder_open,
  --       folder_empty = icons.folder_empty,
  --       -- The next two settings are only a fallback, if you use nvim-web-devicons and configure default icons there
  --       -- then these will never be used.
  --       default = '*',
  --       highlight = 'NeoTreeFileIcon',
  --     },
  --     modified = {
  --       symbol = '[+]',
  --       highlight = 'NeoTreeModified',
  --     },
  --     name = {
  --       trailing_slash = false,
  --       use_git_status_colors = true,
  --       highlight = 'NeoTreeFileName',
  --     },
  --     git_status = {
  --       symbols = {
  --         -- Change type
  --         added = icons.git_add, -- or "✚", but this is redundant info if you use git_status_colors on the name
  --         modified = icons.git_change, -- or "", but this is redundant info if you use git_status_colors on the name
  --         deleted = icons.git_delete, -- this can only be used in the git_status source
  --         renamed = icons.right_arrow, -- this can only be used in the git_status source
  --         -- Status type
  --         untracked = icons.git_untracked,
  --         ignored = icons.skip,
  --         unstaged = icons.error,
  --         staged = icons.check,
  --         conflict = icons.git_conflict,
  --       },
  --     },
  --   },
  --   window = {
  --     position = 'left',
  --     width = 40,
  --     mapping_options = {
  --       noremap = true,
  --       nowait = true,
  --     },
  --     mappings = {
  --       ['<space>'] = {
  --         'toggle_node',
  --         nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
  --       },
  --       ['<2-LeftMouse>'] = 'open',
  --       ['<cr>'] = 'open',
  --       ['h'] = 'close_node',
  --       ['<esc>'] = 'revert_preview',
  --       ['P'] = { 'toggle_preview', config = { use_float = true } },
  --       ['s'] = 'open_split',
  --       ['v'] = 'open_vsplit',
  --       ['t'] = 'open_tabnew',
  --       ['l'] = 'open',
  --       -- ['o'] = 'system_open',
  --       ['C'] = 'close_node',
  --       ['z'] = 'close_all_nodes',
  --       ['a'] = {
  --         'add',
  --         -- this command supports BASH style brace expansion ("x{a,b,c}" -> xa,xb,xc). see `:h neo-tree-file-actions` for details
  --         -- some commands may take optional config options, see `:h neo-tree-mappings` for details
  --         config = {
  --           show_path = 'none', -- "none", "relative", "absolute"
  --         },
  --       },
  --       ['A'] = 'add_directory', -- also accepts the optional config.show_path option like "add". this also supports BASH style brace expansion.
  --       ['d'] = 'delete',
  --       ['r'] = 'rename',
  --       ['y'] = 'copy_to_clipboard',
  --       ['x'] = 'cut_to_clipboard',
  --       ['p'] = 'paste_from_clipboard',
  --       ['c'] = 'copy', -- takes text input for destination, also accepts the optional config.show_path option like "add":
  --       ['m'] = 'move', -- takes text input for destination, also accepts the optional config.show_path option like "add".
  --       ['q'] = 'close_window',
  --       ['R'] = 'refresh',
  --       ['?'] = 'show_help',
  --       ['<'] = 'prev_source',
  --       ['>'] = 'next_source',
  --     },
  --   },
  --   nesting_rules = {},
  --   filesystem = {
  --     filtered_items = {
  --       visible = false, -- when true, they will just be displayed differently than normal items
  --       hide_dotfiles = false,
  --       hide_gitignored = false,
  --       hide_by_name = {
  --         --"node_modules"
  --       },
  --       hide_by_pattern = { -- uses glob style patterns
  --         --"*.meta",
  --         --"*/src/*/tsconfig.json",
  --       },
  --       always_show = { -- remains visible even if other settings would normally hide it
  --         --".gitignored",
  --       },
  --       never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
  --         --".DS_Store",
  --         --"thumbs.db"
  --       },
  --       never_show_by_pattern = { -- uses glob style patterns
  --         --".null-ls_*",
  --       },
  --     },
  --     follow_current_file = { enabled = true }, -- This will find and focus the file in the active buffer every
  --     -- time the current file is changed while the tree is open.
  --     group_empty_dirs = false, -- when true, empty folders will be grouped together
  --     hijack_netrw_behavior = 'open_default', -- netrw disabled, opening a directory opens neo-tree
  --     -- in whatever position is specified in window.position
  --     -- "open_current",  -- netrw disabled, opening a directory opens within the
  --     -- window like netrw would, regardless of window.position
  --     -- "disabled",    -- netrw left alone, neo-tree does not handle opening dirs
  --     use_libuv_file_watcher = true, -- This will use the OS level file watchers to detect changes
  --     -- instead of relying on nvim autocmd events.
  --     window = {
  --       mappings = {
  --         ['<bs>'] = 'navigate_up',
  --         ['.'] = 'set_root',
  --         ['H'] = 'toggle_hidden',
  --         ['/'] = 'fuzzy_finder',
  --         ['D'] = 'fuzzy_finder_directory',
  --         ['#'] = 'fuzzy_sorter', -- fuzzy sorting using the fzy algorithm
  --         -- ["D"] = "fuzzy_sorter_directory",
  --         ['f'] = 'filter_on_submit',
  --         ['<c-x>'] = 'clear_filter',
  --         ['[g'] = 'prev_git_modified',
  --         [']g'] = 'next_git_modified',
  --       },
  --     },
  --   },
  --   buffers = {
  --     follow_current_file = { enabled = true }, -- This will find and focus the file in the active buffer every
  --     -- time the current file is changed while the tree is open.
  --     group_empty_dirs = true, -- when true, empty folders will be grouped together
  --     show_unloaded = true,
  --     window = {
  --       mappings = {
  --         ['bd'] = 'buffer_delete',
  --         ['<bs>'] = 'navigate_up',
  --         ['.'] = 'set_root',
  --       },
  --     },
  --   },
  --   git_status = {
  --     window = {
  --       position = 'float',
  --       mappings = {
  --         ['A'] = 'git_add_all',
  --         ['gu'] = 'git_unstage_file',
  --         ['gs'] = 'git_add_file',
  --         ['gr'] = 'git_revert_file',
  --         ['gc'] = 'git_commit',
  --         ['gp'] = 'git_push',
  --         ['gg'] = 'git_commit_and_push',
  --       },
  --     },
  --   },
  --   event_handlers = {
  --     {
  --       event = 'file_opened',
  --       handler = function(_)
  --         require('neo-tree.command').execute { action = 'close' }
  --       end,
  --     },
  --   },
  -- },
}
