return {
-- 	"otavioschwanck/tmux-awesome-manager.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		local tmux = require("tmux-awesome-manager")
-- 		tmux.setup({
-- 			session_name = "Neovim Terminals",
-- 			use_icon = true,
-- 			icon = " ",
-- 		})
--
-- 		-- local wk = require("which-key")
-- local tmux_term = require('tmux-awesome-manager.src.term')
--
-- 		-- vim.keymap.set("n", "rr", tmux_term.run({ name = "Rails Server", cmd = "bundle exec rails s", visit_first_call = false, open_as = "pane" }), "Start Rails server")
-- 		-- wk.add({
-- 		-- {
-- 		-- {
-- 		-- 	"rr",
-- 		-- 	tmux_term.run_wk({
-- 		-- 		cmd = "bundle exec rails s",
-- 		-- 		name = "Rails Server",
-- 		-- 		visit_first_call = false,
-- 		-- 		open_as = "pane",
-- 		-- 	}),
-- 		-- },
-- 		-- o = tmux_term.run_wk {
-- 		--   cmd = 'overmind start',
-- 		--   name = 'Overmind',
-- 		--   visit_first_call = false,
-- 		--   open_as = 'pane',
-- 		-- },
-- 		-- c = tmux_term.run_wk { cmd = 'bundle exec rails c', name = 'Rails Console', open_as = 'window' },
-- 		-- b = tmux_term.run_wk {
-- 		--   cmd = 'bundle install',
-- 		--   name = 'Bundle Install',
-- 		--   open_as = 'pane',
-- 		--   close_on_timer = 2,
-- 		--   visit_first_call = false,
-- 		--   focus_when_call = false,
-- 		-- },
-- 		-- t = tmux_term.run_wk {
-- 		--   cmd = 'bundle exec rails test',
-- 		--   name = 'Run all minitests',
-- 		--   open_as = 'pane',
-- 		--   visit_first_call = false,
-- 		--   focus_when_call = false,
-- 		-- },
-- 		-- j = tmux_term.run_wk {
-- 		--   cmd = 'yarn test',
-- 		--   name = 'Run all Jest tests',
-- 		--   open_as = 'pane',
-- 		--   visit_first_call = false,
-- 		--   focus_when_call = false,
-- 		-- },
-- 		-- g = tmux_term.run_wk {
-- 		--   cmd = 'bundle exec rails generate %1',
-- 		--   name = 'Rails Generate',
-- 		--   questions = {
-- 		--     {
-- 		--       question = 'Rails generate: ',
-- 		--       required = true,
-- 		--       open_as = 'pane',
-- 		--       close_on_timer = 4,
-- 		--       visit_first_call = false,
-- 		--       focus_when_call = false,
-- 		--     },
-- 		--   },
-- 		-- },
-- 		-- d = tmux_term.run_wk {
-- 		--   cmd = 'bundle exec rails destroy %1',
-- 		--   name = 'Rails Destroy',
-- 		--   questions = {
-- 		--     {
-- 		--       question = 'Rails destroy: ',
-- 		--       required = true,
-- 		--       open_as = 'pane',
-- 		--       close_on_timer = 4,
-- 		--       visit_first_call = false,
-- 		--       focus_when_call = false,
-- 		--     },
-- 		--   },
-- 		-- },
-- 		-- },
-- 		-- },
-- 		-- { prefix = "<leader>", silent = true },
-- 		-- })
-- 	end,
}
