-- HIGHLIGHTS
--

vim.api.nvim_set_hl(0, 'MiniStatusLineInactive', { bg = '#444444' })
vim.api.nvim_set_hl(0, 'MiniStatusLineFilename', { bg = '#444444', fg = '#999999' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#444444', fg = '#888888' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#dddddd' })
vim.api.nvim_set_hl(0, 'SpellBad', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { fg = '#a9b665' })
vim.api.nvim_set_hl(0, 'CmpItemKind', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = '#7daea3' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#e78a4e' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { fg = '#e78a4e' })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', { fg = '#e78a4e' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', { fg = '#89b482' })
vim.api.nvim_set_hl(0, 'FloatTitle', { fg = '#dddddd' })
vim.api.nvim_set_hl(0, 'NVimTreeWindowPicker', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'NONE' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#d4be98' })
vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { fg = '#444444' })
vim.api.nvim_set_hl(0, 'VertSplit', { bg = 'NONE', fg = '#888888' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#444444' })
