require 'vasco.plugins'
require 'vasco.options'
require 'vasco.theme'

require 'vasco.plugins_config.coc'
require 'vasco.plugins_config.statusline'
require 'vasco.plugins_config.nvimtree'
require 'vasco.plugins_config.gitsigns'
require 'vasco.plugins_config.comment'
require 'vasco.plugins_config.treesitter'
require 'vasco.plugins_config.surround'
require 'vasco.plugins_config.telescope'
require 'vasco.plugins_config.highlight'

require 'vasco.mappings'
