# COLORSCHEME: gruvbox light (medium)

THEME_BG=#d4be98
THEME_FG=#282828
THEME_GRAY=#5b534d
THEME_GRAY=#665c54
THEME_DARK_GREY=#3c3836
THEME_GREEN=#000000
THEME_RED=#ea6962
THEME_BLUE=#7daea3
THEME_YELLOW=#d8a657

source-file ~/.tmux/themes/gruvbox.conf
