## COLORSCHEME: gruvbox dark (medium)
set-option -g status "on"
set-option -g status-position top
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "20"
set-option -g status-right-style none
set-option -g status-right-length "250"
set-window-option -g window-status-separator ""
set-window-option -g pane-border-status top
set-window-option -g pane-border-format ''

# default statusbar color
set-option -g status-style bg=#282828,fg=#d4be98 # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=#5b534d #fg2
set-option -g pane-border-style fg=#3c3836 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg

set-option -g status-left "#[bg=#A89984,fg=#282828,bold] #S #[bg=#282828,fg=#A89984,nobold,noitalics,nounderscore]"
set-option -g status-right "#[fg=colour241]#{mpd_now_playing} #{cpu_fg_color}  #{cpu_percentage} #[fg=colour15] #{battery_percentage} #[bg=#282828,fg=#504945,nobold, nounderscore, noitalics]#[bg=#504945,fg=#A89984] #{clima}    %a %d/%m %I:%M%p "

set-window-option -g window-status-current-format "#[bg=#d8a657,fg=#282828,nobold,noitalics,nounderscore]#[bg=#d8a657,fg=colour239] #I #[bg=#d8a657,fg=colour239,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#282828,fg=#d8a657,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#504945,fg=#282828,noitalics]#[bg=#504945,fg=#A89984] #I #[bg=#504945,fg=#A89984] #W #[bg=#282828,fg=#504945,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
