[colors.primary]
background = "#292828"
foreground = "#ebdbb2"

[colors.normal]
black = "#32302f"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#ebdbb2"

[colors.bright]
black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#fbf1c7"
