local map = vim.keymap.set
local opts = { noremap = true, silent = true }
local uv = vim.uv

-- Leader key
vim.g.mapleader = " "

-- Seamless window movement/resizing across Neovim and tmux.
map("n", "<C-h>", function() require("splits").move("left") end, opts)
map("n", "<C-j>", function() require("splits").move("down") end, opts)
map("n", "<C-k>", function() require("splits").move("up") end, opts)
map("n", "<C-l>", function() require("splits").move("right") end, opts)
map("n", "<M-h>", function() require("splits").resize("left") end, opts)
map("n", "<M-j>", function() require("splits").resize("down") end, opts)
map("n", "<M-k>", function() require("splits").resize("up") end, opts)
map("n", "<M-l>", function() require("splits").resize("right") end, opts)

-- Core editing
map("n", "<leader>w", "<cmd>w<CR>", { desc = "Save" })
map("n", "<leader>e", function()
  vim.g.dotfiles_lazy.mini_files()
  require("mini.files").open(vim.api.nvim_buf_get_name(0), true)
end, { desc = "Explorer" })

map("n", "<leader>ql", function()
  if vim.fn.getqflist({ winid = 0 }).winid ~= 0 then
    vim.cmd.cclose()
  else
    vim.cmd.copen()
  end
end, { desc = "Toggle quickfix" })

map("n", "<Esc>", "<cmd>nohlsearch<CR>", opts)

-- Native LSP completion keeps selection explicit: choose an item first, then
-- Enter accepts it. Otherwise Enter retains its normal newline behavior.
map("i", "<C-Space>", function() vim.lsp.completion.get() end, { desc = "Complete" })
map("i", "<C-j>", function()
  return vim.fn.pumvisible() == 1 and "<C-n>" or "<C-j>"
end, { expr = true, desc = "Next completion or newline" })
map("i", "<C-k>", function()
  return vim.fn.pumvisible() == 1 and "<C-p>" or "<C-k>"
end, { expr = true, desc = "Previous completion or digraph" })
map("i", "<C-l>", function()
  if vim.fn.pumvisible() ~= 1 then return "<C-l>" end

  local completion = vim.fn.complete_info({ "selected" })
  return completion.selected >= 0 and "<C-y>" or "<C-n><C-y>"
end, { expr = true, desc = "Accept completion" })
map("i", "<CR>", function()
  local completion = vim.fn.complete_info({ "selected" })
  return vim.fn.pumvisible() == 1 and completion.selected >= 0 and "<C-y>" or "<CR>"
end, { expr = true, desc = "Accept completion or newline" })

local editing_group = vim.api.nvim_create_augroup("DotfilesEditing", { clear = true })
vim.api.nvim_create_autocmd("TextYankPost", {
  group = editing_group,
  callback = function()
    vim.hl.on_yank({ higroup = "IncSearch", timeout = 200 })
  end,
})

-- Tab navigation (<Tab>=<C-i> in terminals, so use leader to preserve jumplist)
map("n", "<leader><Tab>", "gt", { desc = "Next tab" })
map("n", "<leader><S-Tab>", "gT", { desc = "Prev tab" })

-- Navigation (Flash)
map({ "n", "x", "o" }, "s", function()
  vim.g.dotfiles_lazy.flash()
  require("flash").jump()
end, { desc = "Flash" })

-- Fzf-lua
-- Each picker loads fzf-lua on first use.
local function fzf(command, fzf_opts)
  return function()
    vim.g.dotfiles_lazy.fzf()
    require("fzf-lua")[command](fzf_opts)
  end
end

-- LSP
-- ruby-lsp can't resolve some metaprogrammed DSL methods (`validates`,
-- `acts_as_list`, ...); when the LSP has no answer, fall back to the tags
-- generated by :GemTags.
local function definition_or_tag()
  local bufnr = vim.api.nvim_get_current_buf()
  local winid = vim.api.nvim_get_current_win()
  local cursor = vim.api.nvim_win_get_cursor(winid)
  local changedtick = vim.api.nvim_buf_get_changedtick(bufnr)
  local word = vim.fn.expand("<cword>")

  local function context_valid()
    return vim.api.nvim_buf_is_valid(bufnr)
      and vim.api.nvim_win_is_valid(winid)
      and vim.api.nvim_win_get_buf(winid) == bufnr
      and vim.api.nvim_buf_get_changedtick(bufnr) == changedtick
      and vim.deep_equal(vim.api.nvim_win_get_cursor(winid), cursor)
  end

  local function tag_fallback()
    if not context_valid() then return end
    -- LSP attach sets tagfunc back to the LSP; clear it so tjump reads the
    -- tags files instead.
    local root = vim.fs.root(vim.api.nvim_buf_get_name(bufnr), { "Gemfile", ".git" })
    local tag_file = require("tags").path(root)
    local ok = tag_file and pcall(vim.api.nvim_win_call, winid, function()
      require("tags").with_file(bufnr, tag_file, function()
        local tagfunc = vim.bo[bufnr].tagfunc
        vim.bo[bufnr].tagfunc = ""
        local jumped = pcall(vim.cmd.tjump, word)
        vim.bo[bufnr].tagfunc = tagfunc
        if not jumped then error("tag not found") end
      end)
    end)
    if not ok then
      vim.notify("No definition or tag for '" .. word .. "' (:GemTags to index gems)", vim.log.levels.WARN)
    end
  end
  local clients = vim.lsp.get_clients({ bufnr = 0, method = "textDocument/definition" })
  if #clients == 0 then return tag_fallback() end
  vim.lsp.buf_request_all(bufnr, "textDocument/definition", function(client)
    return vim.lsp.util.make_position_params(winid, client.offset_encoding)
  end, function(results)
    if not context_valid() then return end
    for _, res in pairs(results) do
      local r = res.result
      if r and (r.uri or not vim.tbl_isempty(r)) then
        vim.api.nvim_win_call(winid, function()
          vim.g.dotfiles_lazy.fzf()
          require("fzf-lua").lsp_definitions({ jump1 = true })
        end)
        return
      end
    end
    tag_fallback()
  end)
end
map("n", "gd", definition_or_tag, { desc = "Go to definition" })
map("n", "grr", fzf("lsp_references"), { desc = "References" })
map("n", "gri", fzf("lsp_implementations", { jump1 = true }), { desc = "Implementations" })
map("n", "K", function() vim.lsp.buf.hover() end, { desc = "Hover docs" })
map("n", "<leader>ca", function() vim.lsp.buf.code_action() end, { desc = "Code action" })
map("n", "<leader>cr", function() vim.lsp.buf.rename() end, { desc = "Rename symbol" })
map("n", "<leader>cf", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format buffer" })
map("n", "<leader>ch", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = 0 }), { bufnr = 0 })
end, { desc = "Toggle inlay hints" })

map("n", "<leader>fb", fzf("buffers"), { desc = "Buffers" })
map("n", "<leader>ff", fzf("files"), { desc = "Files" })
map("n", "<leader>fs", fzf("lsp_document_symbols"), { desc = "Document symbols" })
map("n", "<leader>fg", fzf("live_grep"), { desc = "Grep" })
map("n", "<leader>fw", fzf("grep_cword"), { desc = "Grep word" })
map("n", "<leader>fr", fzf("resume"), { desc = "Resume" })

require("git.keymaps").setup(fzf)

-- Rails/Ruby
local function rails_find_files(cwd, prompt_title)
  if uv.fs_stat(cwd) == nil then
    vim.notify(("Missing directory: %s"):format(cwd), vim.log.levels.WARN)
    return
  end
  vim.g.dotfiles_lazy.fzf()
  require("fzf-lua").files({ cwd = cwd, prompt = prompt_title .. "> " })
end

map("n", "<leader>rm", function() rails_find_files("app/models", "Models") end, { desc = "Find Models" })
map("n", "<leader>rc", function() rails_find_files("app/controllers", "Controllers") end, { desc = "Find Controllers" })
map("n", "<leader>rv", function() rails_find_files("app/views", "Views") end, { desc = "Find Views" })
map("n", "<leader>rs", function() rails_find_files("spec", "Specs") end, { desc = "Find Specs" })

-- Testing
map("n", "<leader>tr", function()
  vim.g.dotfiles_lazy.neotest()
  require("neotest").run.run()
end, { desc = "Run nearest" })
map("n", "<leader>tf", function()
  vim.g.dotfiles_lazy.neotest()
  require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Run file" })
map("n", "<leader>tt", function()
  vim.g.dotfiles_lazy.neotest()
  require("neotest").summary.toggle()
end, { desc = "Toggle summary" })
map("n", "<leader>tl", function()
  vim.g.dotfiles_lazy.neotest()
  require("neotest").run.run_last()
end, { desc = "Run last" })
map("n", "<leader>to", function()
  vim.g.dotfiles_lazy.neotest()
  require("neotest").output.open({ enter = true })
end, { desc = "Show output" })

-- AI (agentic.nvim)
-- Wrap agentic.nvim calls so the plugin only loads when an AI mapping is used.
local function agentic(fn, ...)
  local args = { ... }
  return function()
    vim.g.dotfiles_lazy.agentic()
    require("agentic")[fn](unpack(args))
  end
end

map({ "n", "v" }, "<leader>aa", agentic("toggle"), { desc = "Toggle chat" })
map({ "n", "v" }, "<leader>ac", agentic("add_selection_or_file_to_context"), { desc = "Add file/selection to context" })
map("n", "<leader>ad", agentic("add_current_line_diagnostics"), { desc = "Add line diagnostics" })
map("n", "<leader>aD", agentic("add_buffer_diagnostics"), { desc = "Add buffer diagnostics" })
map("n", "<leader>an", agentic("new_session"), { desc = "New session" })
map("n", "<leader>ar", agentic("restore_session"), { desc = "Restore session" })
map("n", "<leader>as", agentic("stop_generation"), { desc = "Stop generation" })
map("n", "<leader>ap", agentic("switch_provider"), { desc = "Switch provider" })
map("n", "<leader>al", agentic("rotate_layout"), { desc = "Rotate layout" })

-- UI
map("n", "<leader>cx", function()
  local list = vim.fn.getqflist({ title = 0, winid = 0 })
  if list.winid ~= 0 and list.title == "Diagnostics" then
    vim.cmd.cclose()
  else
    vim.diagnostic.setqflist({ title = "Diagnostics", open = true })
  end
end, { desc = "Diagnostics" })
map("n", "<leader>co", fzf("lsp_document_symbols"), { desc = "Document outline" })
map("n", "<leader>fS", function()
  vim.g.dotfiles_lazy.grug_far()
  require("grug-far").open()
end, { desc = "Search & Replace" })

-- Pack management
vim.api.nvim_create_user_command("PackUpdate", function()
  require("packs").install_all()
  vim.pack.update()
end, { desc = "Update plugins", force = true })
vim.api.nvim_create_user_command("PackRestore", function()
  require("packs").install_all()
  vim.pack.update(nil, { target = "lockfile" })
end, { desc = "Restore plugins from lockfile", force = true })
map("n", "<leader>pu", "<cmd>PackUpdate<cr>", { desc = "Update plugins" })
map("n", "<leader>ps", "<cmd>PackRestore<cr>", { desc = "Restore plugins from lockfile" })
