local M = {}
local paths = {}

function M.path(root)
  if not root or root == "" then return nil end
  if paths[root] then return paths[root] end

  local result = vim.system({
    "git", "-C", root, "rev-parse", "--path-format=absolute", "--git-path", "tags",
  }, { text = true }):wait()
  local path = result.code == 0 and vim.trim(result.stdout or "") or ""
  if path == "" then path = root .. "/tags" end
  paths[root] = path
  return path
end

function M.with_file(bufnr, path, callback)
  return vim.api.nvim_buf_call(bufnr, function()
    local original = vim.bo[bufnr].tags
    local escaped = vim.fn.fnameescape(path):gsub(",", "\\,")
    vim.bo[bufnr].tags = escaped .. "," .. original
    local result = { pcall(callback) }
    vim.bo[bufnr].tags = original
    if not result[1] then error(result[2]) end
    return unpack(result, 2)
  end)
end

-- Go to definition via LSP, falling back to the tags generated by :GemTags.
-- ruby-lsp can't resolve some metaprogrammed DSL methods (`validates`,
-- `acts_as_list`, ...); when the LSP has no answer, tjump reads the tags.
function M.definition_or_tag()
  local bufnr = vim.api.nvim_get_current_buf()
  local winid = vim.api.nvim_get_current_win()
  local cursor = vim.api.nvim_win_get_cursor(winid)
  local changedtick = vim.api.nvim_buf_get_changedtick(bufnr)
  local word = vim.fn.expand("<cword>")

  local function context_valid()
    return vim.api.nvim_buf_is_valid(bufnr)
      and vim.api.nvim_win_is_valid(winid)
      and vim.api.nvim_get_current_win() == winid
      and vim.api.nvim_win_get_buf(winid) == bufnr
      and vim.api.nvim_buf_get_changedtick(bufnr) == changedtick
      and vim.deep_equal(vim.api.nvim_win_get_cursor(winid), cursor)
  end

  local function tag_fallback()
    if not context_valid() then return end
    -- LSP attach sets tagfunc back to the LSP; clear it so tjump reads the
    -- tags files instead.
    local root = vim.fs.root(vim.api.nvim_buf_get_name(bufnr), { "Gemfile", ".git" })
    local tag_file = M.path(root)
    local ok = tag_file and pcall(vim.api.nvim_win_call, winid, function()
      M.with_file(bufnr, tag_file, function()
        local tagfunc = vim.bo[bufnr].tagfunc
        vim.bo[bufnr].tagfunc = ""
        local jumped = pcall(vim.cmd.tjump, word)
        vim.bo[bufnr].tagfunc = tagfunc
        if not jumped then error("tag not found") end
      end)
    end)
    if not ok then
      vim.notify("No definition or tag for '" .. word .. "' (:GemTags to index gems)", vim.log.levels.WARN)
    end
  end

  local clients = vim.lsp.get_clients({ bufnr = 0, method = "textDocument/definition" })
  if #clients == 0 then return tag_fallback() end
  vim.lsp.buf_request_all(bufnr, "textDocument/definition", function(client)
    return vim.lsp.util.make_position_params(winid, client.offset_encoding)
  end, function(results)
    if not context_valid() then return end
    for _, res in pairs(results) do
      local r = res.result
      if r and (r.uri or not vim.tbl_isempty(r)) then
        require("lazyload").fzf()
        require("fzf-lua").lsp_definitions({ jump1 = true })
        return
      end
    end
    tag_fallback()
  end)
end

-- Tag the project and every bundled gem with ripper-tags so `gd` can fall
-- back to tags for definitions ruby-lsp can't resolve. Resolve the Git tags
-- path through Git itself so linked worktrees are supported.
local function generate_gem_tags()
  local root = vim.fs.root(0, "Gemfile")
  if not root then
    vim.notify("No Gemfile found", vim.log.levels.WARN)
    return
  end
  local tag_file = M.path(root)
  -- ripper-tags occasionally emits an entry with an embedded newline, which
  -- makes Vim reject the whole file (E431); drop malformed lines afterwards.
  local quoted = vim.fn.shellescape(tag_file)
  local sanitize = string.format(
    [[LC_ALL=C awk -F'\t' 'NF>=3' %s > %s.tmp && mv %s.tmp %s]],
    quoted, quoted, quoted, quoted
  )
  local function done(msg, level)
    vim.schedule(function()
      vim.g.gemtags_running = nil
      vim.notify(msg, level)
      vim.cmd.redrawstatus()
    end)
  end
  vim.g.gemtags_running = true
  vim.cmd.redrawstatus()
  vim.system({ "mise", "x", "--", "bundle", "list", "--paths" }, { cwd = root, text = true }, function(list)
    if list.code ~= 0 then
      done("bundle list failed:\n" .. (list.stderr or ""), vim.log.levels.ERROR)
      return
    end
    local cmd = {
      "mise", "x", "--", "ripper-tags", "-R", "--tag-file", tag_file,
      "--exclude=vendor", "--exclude=node_modules", root,
    }
    vim.list_extend(cmd, vim.split(vim.trim(list.stdout), "\n"))
    vim.system(cmd, { cwd = root, text = true }, function(res)
      if res.code ~= 0 then
        done("ripper-tags failed (gem install ripper-tags?):\n" .. (res.stderr or ""), vim.log.levels.ERROR)
        return
      end
      vim.system({ "sh", "-c", sanitize }, {}, function(s)
        if s.code == 0 then
          done("Tags written to " .. tag_file)
        else
          done("tags sanitize failed:\n" .. (s.stderr or ""), vim.log.levels.ERROR)
        end
      end)
    end)
  end)
end

function M.setup()
  vim.api.nvim_create_user_command("GemTags", generate_gem_tags, {
    desc = "Generate tags for project and bundled gems",
    force = true,
  })
end

return M
