local M = {
  arrow_right = '▶',
  cog = ' ',
  error = ' ',
  warning = ' ',
  hint = '󰌵 ',
  info = ' ',
  check = ' ',
  minus = ' ',
  plus = ' ',
  git_add = ' ',
  git_change = ' ',
  git_delete = ' ',
  git_untracked = '★',
  git_conflict = ' ',
  right_arrow = ' ',
  down_arrow = ' ',
  breakpoint = ' ',
  folder_closed = ' ',
  folder_open = ' ',
  folder_symlink = ' ',
  bulb = '󰌵 ',
  skip = ' ',
  question = ' ',
  document = '󰈙 ',
  symlink = ' ',
  search = '   ',
  breadcrumb = '',
  git = ' ',
  copilot = ' ',
}

return M
