# Vimbox colour theme based (dark)

background #262626
foreground #dab997
selection_background #dab997
selection_foreground #262626
url_color #84adad
cursor #dab997
active_border_color #8a8a8a
inactive_border_color #444444
active_tab_background #262626
active_tab_foreground #afaf00
inactive_tab_background #262626
inactive_tab_foreground #8a8a8a
tab_bar_background none
active_tab_font_style bold
inactive_tab_font_style normal

color0 #262626
color1 #d75f5f
color2 #afaf00
color3 #ffaf00
color4 #83adad
color5 #d485ad
color6 #85ad85
color7 #dab997
color8 #8a8a8a
color9 #d75f5f
color10 #afaf00
color11 #ffaf00
color12 #83adad
color13 #d485ad
color14 #85ad85
color15 #ebdbb2
