# Vimbox colour theme based (dark)

background #2c323b
foreground #dab997
selection_background #dab997
selection_foreground #2c323b
url_color #84adad
cursor #dab997
active_border_color #8a8a8a
inactive_border_color #444444
active_tab_background #2c323b
active_tab_foreground #afaf00
inactive_tab_background #2c323b
inactive_tab_foreground #8a8a8a
tab_bar_background none
active_tab_font_style bold
inactive_tab_font_style normal

color0 #2c323b
color1 #d75f5f
color2 #afaf00
color3 #e5c07b
color4 #83adad
color5 #d485ad
color6 #85ad85
color7 #dab997
color8 #8a8a8a
color9 #d75f5f
color10 #afaf00
color11 #e5c07b
color12 #83adad
color13 #d485ad
color14 #85ad85
color15 #dab997
