# Vimbox colour theme based (light)

background #ebdbb2
foreground #262626
selection_background #262626
selection_foreground #ebdbb2
url_color #84adad
cursor #262626
active_border_color #262626
inactive_border_color #8a8a8a
active_tab_background #ebdbb2
active_tab_foreground #afaf00
inactive_tab_background #ebdbb2
inactive_tab_foreground #8a8a8a
tab_bar_background #ebdbb2

color0 #ebdbb2
color1 #d75f5f
color2 #afaf00
color3 #ffaf00
color4 #83adad
color5 #d485ad
color6 #85ad85
color7 #262626
color8 #8a8a8a
color9 #d75f5f
color10 #afaf00
color11 #ffaf00
color12 #83adad
color13 #d485ad
color14 #85ad85
color15 #ebdbb2
