# Vimbox colour theme based (light)

background #dab997
foreground #2c323b
selection_background #2c323b
selection_foreground #dab997
url_color #84adad
cursor #2c323b
active_border_color #2c323b
inactive_border_color #8a8a8a
active_tab_background #dab997
active_tab_foreground #afaf00
inactive_tab_background #dab997
inactive_tab_foreground #8a8a8a
tab_bar_background #dab997

color0 #dab997
color1 #d75f5f
color2 #afaf00
color3 #e5c07b
color4 #83adad
color5 #d485ad
color6 #85ad85
color7 #2c323b
color8 #8a8a8a
color9 #d75f5f
color10 #afaf00
color11 #e5c07b
color12 #83adad
color13 #d485ad
color14 #85ad85
color15 #dab997
